//
//  GreetingWorker.swift
//  CleanSwiftApp
//
//  Created by Константин Прокофьев on 26.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

final class GreetingConfigurator {
    
    static let shared = GreetingConfigurator()
    
    private init() {}
    
    func configur(with viewController: GreetingViewController) {
        let viewController = viewController
        let interactor = GreetingInteractor()
        let presenter = GreetingPresenter()
        viewController.interactor = interactor
        interactor.presenter = presenter
        presenter.viewController = viewController
  }
}
